# Generated by Django 3.2 on 2021-04-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210420_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='temperature_expected',
            field=models.IntegerField(default=26),
            preserve_default=False,
        ),
    ]
